--[[
This is the main S2E configuration file
=======================================

This file was automatically generated by s2e-env at 2025-10-31 18:18:08.954264

Changes can be made by the user where appropriate.
]]--

-------------------------------------------------------------------------------
-- This section configures the S2E engine.
s2e = {
    logging = {
        -- Possible values include "all", "debug", "info", "warn" and "none".
        -- See Logging.h in libs2ecore.
        console = "debug",
        logLevel = "debug",
    },

    -- All the cl::opt options defined in the engine can be tweaked here.
    -- This can be left empty most of the time.
    -- Most of the options can be found in S2EExecutor.cpp and Executor.cpp.
    kleeArgs = {
    },
}

-- Declare empty plugin settings. They will be populated in the rest of
-- the configuration file.
plugins = {}
pluginsConfig = {}

-- Include various convenient functions
dofile('library.lua')

-------------------------------------------------------------------------------
-- This plugin contains the core custom instructions.
-- Some of these include s2e_make_symbolic, s2e_kill_state, etc.
-- You always want to have this plugin included.

add_plugin("BaseInstructions")
pluginsConfig.BaseInstructions = {

}

-------------------------------------------------------------------------------
-- This plugin implements "shared folders" between the host and the guest.
-- Use it in conjunction with s2eget and s2eput guest tools in order to
-- transfer files between the guest and the host.

add_plugin("HostFiles")
pluginsConfig.HostFiles = {
    baseDirs = {
        "/home/s2e/cco_s2e/projects/3faec97133d90f5e1dfae64866656704e2a92b12",

    },
    allowWrite = true,
}

-------------------------------------------------------------------------------
-- This plugin provides support for virtual machine introspection and binary
-- formats parsing. S2E plugins can use it when they need to extract
-- information from binary files that are either loaded in virtual memory
-- or stored on the host's file system.

add_plugin("Vmi")
pluginsConfig.Vmi = {
    baseDirs = {
        "/home/s2e/cco_s2e/projects/3faec97133d90f5e1dfae64866656704e2a92b12",


            "/home/s2e/cco_s2e/images/buildroot-6.4.1/rootfs",


    },
}

-------------------------------------------------------------------------------
-- This plugin provides various utilities to read from process memory.
-- In case it is not possible to read from guest memory, the plugin tries
-- to read static data from binary files stored in guestfs.
add_plugin("MemUtils")

-------------------------------------------------------------------------------
-- This plugin collects various execution statistics and sends them to a QMP
-- server that listens on an address:port configured by the S2E_QMP_SERVER
-- environment variable.
--
-- The "s2e run 3faec97133d90f5e1dfae64866656704e2a92b12" command sets up such a server in order to display
-- stats on the dashboard.
--
-- You may also want to use this plugin to integrate S2E into a larger
-- system. The server could collect information about execution from different
-- S2E instances, filter them, and store them in a database.

add_plugin("WebServiceInterface")
pluginsConfig.WebServiceInterface = {
    statsUpdateInterval = 2
}

-------------------------------------------------------------------------------
-- This is the main execution tracing plugin.
-- It generates the ExecutionTracer.dat file in the s2e-last folder.
-- That files contains trace information in a binary format. Other plugins can
-- hook into ExecutionTracer in order to insert custom tracing data.
--
-- This is a core plugin, you most likely always want to have it.

add_plugin("ExecutionTracer")

-------------------------------------------------------------------------------
-- This plugin records events about module loads/unloads and stores them
-- in ExecutionTracer.dat.
-- This is useful in order to map raw program counters and pids to actual
-- module names.

add_plugin("ModuleTracer")

-------------------------------------------------------------------------------
-- This is a generic plugin that let other plugins communicate with each other.
-- It is a simple key-value store.
--
-- The plugin has several modes of operation:
--
-- 1. local: runs an internal store private to each instance (default)
-- 2. distributed: the plugin interfaces with an actual key-value store server.
-- This allows different instances of S2E to communicate with each other.

add_plugin("KeyValueStore")

-------------------------------------------------------------------------------
-- Records statistics into s2e-last/stats.csv.
-- This corresponds to the old klee run.stats file.
add_plugin("StatsTracker")

-------------------------------------------------------------------------------
-- Records the program counter of executed translation blocks.
-- Generates a json coverage file. This file can be later processed by other
-- tools to generate line coverage information. Please refer to the S2E
-- documentation for more details.

add_plugin("TranslationBlockCoverage")
pluginsConfig.TranslationBlockCoverage = {
    writeCoverageOnStateKill = true,
    writeCoverageOnStateSwitch = true,
}

-------------------------------------------------------------------------------
-- Tracks execution of specific modules.
-- Analysis plugins are often interested only in small portions of the system,
-- typically the modules under analysis. This plugin filters out all core
-- events that do not concern the modules under analysis. This simplifies
-- code instrumentation.
-- Instead of listing individual modules, you can also track all modules by
-- setting configureAllModules = true

add_plugin("ModuleExecutionDetector")
pluginsConfig.ModuleExecutionDetector = {

    mod_0 = {
        moduleName = "repro-3faec97133d90f5e1dfae64866656704e2a92b12",
    },

    logLevel="info"
}

-------------------------------------------------------------------------------
-- This plugin controls the forking behavior of S2E.

add_plugin("ForkLimiter")
pluginsConfig.ForkLimiter = {
    -- How many times each program counter is allowed to fork.
    -- -1 for unlimited.
    maxForkCount = -1,

    -- How many seconds to wait before allowing an S2E process
    -- to spawn a child. When there are many states, S2E may
    -- spawn itself into multiple processes in order to leverage
    -- multiple cores on the host machine. When an S2E process A spawns
    -- a process B, A and B each get half of the states.
    --
    -- In some cases, when states fork and terminate very rapidly,
    -- one can see flash crowds of S2E instances. This decreases
    -- execution efficiency. This parameter forces S2E to wait a few
    -- seconds so that more states can accumulate in an instance
    -- before spawning a process.
    processForkDelay = 5,
}

-------------------------------------------------------------------------------
-- This plugin tracks execution of processes.
-- This is the preferred way of tracking execution and will eventually replace
-- ModuleExecutionDetector.

add_plugin("ProcessExecutionDetector")
pluginsConfig.ProcessExecutionDetector = {
    moduleNames = {

        "repro-3faec97133d90f5e1dfae64866656704e2a92b12",

    },
}

-------------------------------------------------------------------------------
-- Keeps for each state/process an updated map of all the loaded modules.
add_plugin("ModuleMap")
pluginsConfig.ModuleMap = {
  logLevel = "info"
}


-------------------------------------------------------------------------------
-- Keeps for each process in ProcessExecutionDetector an updated map
-- of memory regions.
add_plugin("MemoryMap")
pluginsConfig.MemoryMap = {
  logLevel = "info"
}



-------------------------------------------------------------------------------
-- MultiSearcher is a top-level searcher that allows switching between
-- different sub-searchers.
add_plugin("MultiSearcher")

-- CUPA stands for Class-Uniform Path Analysis. It is a searcher that groups
-- states into classes. Each time the searcher needs to pick a state, it first
-- chooses a class, then picks a state in that class. Classes can further be
-- subdivided into subclasses.
--
-- The advantage of CUPA over other searchers is that it gives similar weights
-- to different parts of the program. If one part forks a lot, a random searcher
-- would most likely pick a state from that hotspot, decreasing the probability
-- of choosing another state that may have better chance of covering new code.
-- CUPA avoids this problem by grouping similar states together.

add_plugin("CUPASearcher")
pluginsConfig.CUPASearcher = {
    -- The order of classes is important, please refer to the plugin
    -- source code and documentation for details on how CUPA works.
    classes = {


        -- This ensures that states run for a certain amount of time.
        -- Otherwise too frequent state switching may decrease performance.
        "batch",



        -- A program under test may be composed of several binaries.
        -- We want to give equal chance to all binaries, even if some of them
        -- fork a lot more than others.
        "pagedir",

        -- Finally, group states by program counter at fork.
        "pc",
    },
    logLevel="info",
    enabled = true,

    -- Delay (in seconds) before switching states (when used with the "batch" class).
    -- A very large delay becomes similar to DFS (current state keeps running
    -- until it is terminated).
    batchTime = 5
}





-------------------------------------------------------------------------------
-- Function models help drastically reduce path explosion. A model is an
-- expression that efficiently encodes the behavior of a function. In imperative
-- languages, functions often have if-then-else branches and loops, which
-- may cause path explosion. A model compresses this into a single large
-- expression. Models are most suitable for side-effect-free functions that
-- fork a lot. Please refer to models.lua and the documentation for more details.

add_plugin("StaticFunctionModels")

pluginsConfig.StaticFunctionModels = {
  modules = {}
}

g_function_models = {}
safe_load('models.lua')
pluginsConfig.StaticFunctionModels.modules = g_function_models


-------------------------------------------------------------------------------
-- This generates test cases when a state crashes or terminates.
-- If symbolic inputs consist of symbolic files, the test case generator writes
-- concrete files in the S2E output folder. These files can be used to
-- demonstrate the crash in a program, added to a test suite, etc.

add_plugin("TestCaseGenerator")
pluginsConfig.TestCaseGenerator = {
    generateOnStateKill = true,
    generateOnSegfault = true
}





-------------------------------------------------------------------------------
-- The screenshot plugin records a screenshot of the guest into screenshotX.png,
-- where XX is the path number. You can configure the interval here:
add_plugin("Screenshot")
pluginsConfig.Screenshot = {
    period = 5
}





-- ========================================================================= --
-- ============== Target-specific configuration begins here. =============== --
-- ========================================================================= --

-------------------------------------------------------------------------------
-- LinuxMonitor is a plugin that monitors Linux events and exposes them
-- to other plugins in a generic way. Events include process load/termination,
-- thread events, signals, etc.
--
-- LinuxMonitor requires a custom Linux kernel with S2E extensions. This kernel
-- (and corresponding VM image) can be built with S2E tools. Please refer to
-- the documentation for more details.

add_plugin("LinuxMonitor")
pluginsConfig.LinuxMonitor = {
    -- Kill the execution state when it encounters a segfault
    terminateOnSegfault = true,

    -- Kill the execution state when it encounters a trap
    terminateOnTrap = true,
}



-- ========================================================================= --
-- ============== User-specific scripts begin here ========================= --
-- ========================================================================= --


-------------------------------------------------------------------------------
-- This plugin exposes core S2E engine functionality to LUA scripts.
-- In particular, it provides the g_s2e global variable, which works similarly
-- to C++ plugins.
-------------------------------------------------------------------------------
add_plugin("LuaBindings")

-------------------------------------------------------------------------------
-- Exposes S2E engine's core event.
-- These are similar to events in CorePlugin.h. Please refer to
-- the LuaCoreEvents.cpp source file for a list of availble events.
-------------------------------------------------------------------------------
add_plugin("LuaCoreEvents")

-- This configuration shows an example that kills states if they fork in
-- a specific module.
--[[
pluginsConfig.LuaCoreEvents = {
    -- This annotation is called in case of a fork. It should return true
    -- to allow the fork and false to prevent it.
    onStateForkDecide = "onStateForkDecide"
}

function onStateForkDecide(state)
   mmap = g_s2e:getPlugin("ModuleMap")
   mod = mmap:getModule(state)
   if mod ~= nil then
      name = mod:getName()
      if name == "mymodule" then
          state:kill(0, "forked in mymodule")
      end

      if name == "myothermodule" then
          return false
      end
   end
   return true
end
--]]
-- 3faec97133d90f5e1dfae64866656704e2a92b12

add_plugin("kdo")
pluginsConfig.kdo = {
    symbolic = true,
    kdo_id = "3faec97133d90f5e1dfae64866656704e2a92b12",
    kdo_store_hook_callid = 254361,
    kdo_store_hook_addr = 0xffffffff87bb02d0,
    kdo_post_store_hook_addr = 0xffffffff87bb0490,
    kdo_store_ctr = 0,

    kdo_asan_memop_callid = 4188,
    kdo_asan_memcpy_addr = 0xffffffff87bb0540,
    kdo_asan_memmov_addr = 0xffffffff87bb04a0,
    kdo_asan_memop_ctr = 0,

    kdo_copy_from_user_addr = 0xffffffff87bb05e0,

    kdo_counterfeit_data_size = 1024,

    kdo_target_object_offset = 0x20,

    kdo_corruption_location = 0x4049cb,

    kdo_memop_type = "memcpy",

    kdo_syscall_type = "different",

    kdo_fork_state = false,

    kdo_cfu_id_list = {
        21982,
	2941,
	16027,
	11017,
	13581
    },

    [21982]={0, 3, 4, 5, 7, 8, 9},
[2941]={2},
[16027]={0, 32, 34, 33, 128, 16},
[11017]={1},
[13581]={0},

    filter_addr_start = {
        0xffffffff81b2bf80, --____kasan_kfree_large
        0xffffffff81b2bde0, --____kasan_slab_free
        0xffffffff81b2c4a0, --__kasan_check_byte
        0xffffffff81b2eeb0, --__kasan_check_read
        0xffffffff81b2eed0, --__kasan_check_write
        0xffffffff81b2bdb0, --__kasan_init_slab_obj
        0xffffffff81b2bf80, --____kasan_kfree_large
        0xffffffff81b2bee0, --__kasan_kfree_large
        0xffffffff81b2c2a0, --__kasan_kmalloc
        0xffffffff81b2c330, --__kasan_kmalloc_large
        0xffffffff81b2c330, --__kasan_kmalloc_large
        0xffffffff81b2c3d0, --__kasan_krealloc
        0xffffffff81b2bd90, --__kasan_poison_object_data
        0xffffffff81b2bcb0, --__kasan_poison_pages
        0xffffffff81b2bce0, --__kasan_poison_slab
        0xffffffff81b2f690, --__kasan_poison_vmalloc
        0xffffffff81b2c240, --__kasan_slab_alloc
        0xffffffff81b2bde0, --____kasan_slab_free
        0xffffffff81b2c020, --__kasan_slab_free_mempool
        0xffffffff81b2bdd0, --__kasan_slab_free
        0xffffffff81b2c020, --__kasan_slab_free_mempool
        0xffffffff81b2bd70, --__kasan_unpoison_object_data
        0xffffffff81b2bd50, --__kasan_unpoison_object_data_default
        0xffffffff81b2bd50, --__kasan_unpoison_object_data_default
        0xffffffff81b2bc80, --__kasan_unpoison_pages
        0xffffffff81b2bc50, --__kasan_unpoison_pages_default
        0xffffffff81b2bc50, --__kasan_unpoison_pages_default
        0xffffffff81b2bbf0, --__kasan_unpoison_range_default
        0xffffffff81b2bc00, --__kasan_unpoison_range
        0xffffffff81b2bbf0, --__kasan_unpoison_range_default
        0xffffffff81b2f610, --__kasan_unpoison_vmalloc
        0xffffffff87bb0540, --__kdo_asan_memcpy
        0xffffffff87bb04a0, --__kdo_asan_memmove
        0xffffffff8c9f4a30, --early_kasan_fault
        0xffffffff81b2d6f0, --kasan_add_zero_shadow
        0xffffffff81b2ba20, --kasan_addr_to_slab
        0xffffffff81b2db60, --kasan_byte_accessible
        0xffffffff81b2e320, --kasan_cache_create
        0xffffffff81b2db90, --kasan_cache_shrink
        0xffffffff81b2dba0, --kasan_cache_shutdown
        0xffffffff81b2d740, --kasan_check_range
        0xffffffff81b2e6f0, --kasan_complete_mode_report_info
        0xffffffff81b301e0, --kasan_cpu_offline
        0xffffffff81b301c0, --kasan_cpu_online
        0xffffffff8c9f4b40, --kasan_cpu_quarantine_init
        0xffffffff81b2f590, --kasan_depopulate_vmalloc_pte
        0xffffffff81b2bbd0, --kasan_disable_current
        0xffffffff8c9ba5e0, --kasan_early_init
        0xffffffff81b2bbb0, --kasan_enable_current
        0xffffffff81b2e650, --kasan_find_first_bad_addr
        0xffffffff81b2e400, --kasan_get_alloc_meta
        0xffffffff81b2e6a0, --kasan_get_alloc_size
        0xffffffff81b2e420, --kasan_get_free_meta
        0xffffffff8c9ba960, --kasan_init
        0xffffffff81b2bdb0, --__kasan_init_slab_obj
        0xffffffff81b2e440, --kasan_init_object_meta
        0xffffffff81b2e440, --kasan_init_object_meta
        0xffffffff8c9ba700, --kasan_map_early_shadow
        0xffffffff87c52620, --kasan_mem_notifier
        0xffffffff8c9f4b10, --kasan_memhotplug_init
        0xffffffff81b2e900, --kasan_metadata_fetch_row
        0xffffffff81b2e470, --kasan_metadata_size
        0xffffffff81b2e310, --kasan_never_merge
        0xffffffff81b2bcb0, --__kasan_poison_pages
        0xffffffff81b2f690, --__kasan_poison_vmalloc
        0xffffffff81b2bce0, --__kasan_poison_slab
        0xffffffff81b2bd90, --__kasan_poison_object_data
        0xffffffff81b2f010, --kasan_poison
        0xffffffff81b2f060, --kasan_poison_last_granule
        0xffffffff81b2f060, --kasan_poison_last_granule
        0xffffffff87bda1c0, --kasan_populate_early_shadow
        0xffffffff8c9f4b30, --kasan_populate_early_vm_area_shadow
        0xffffffff8c9bacd0, --kasan_populate_p4d
        0xffffffff8c9bb050, --kasan_populate_pmd
        0xffffffff8c9bae20, --kasan_populate_pud
        0xffffffff8c9ba890, --kasan_populate_shadow
        0xffffffff8c9ba830, --kasan_populate_shadow_for_vaddr
        0xffffffff8c9ba830, --kasan_populate_shadow_for_vaddr
        0xffffffff81b2f1e0, --kasan_populate_vmalloc_pte
        0xffffffff81b2f170, --kasan_populate_vmalloc
        0xffffffff81b2f1e0, --kasan_populate_vmalloc_pte
        0xffffffff81b2f340, --kasan_populate_vmemmap_pte
        0xffffffff81b2f2e0, --kasan_populate_vmemmap
        0xffffffff81b2f340, --kasan_populate_vmemmap_pte
        0xffffffff81b2e9a0, --kasan_print_address_stack_frame
        0xffffffff81b2e930, --kasan_print_aux_stacks
        0xffffffff81b2f780, --kasan_quarantine_put
        0xffffffff81b2f9b0, --kasan_quarantine_reduce
        0xffffffff81b2fbd0, --kasan_quarantine_remove_cache
        0xffffffff81b2e560, --kasan_record_aux_stack_noalloc
        0xffffffff81b2e4c0, --kasan_record_aux_stack
        0xffffffff81b2e560, --kasan_record_aux_stack_noalloc
        0xffffffff81b2f4e0, --kasan_release_vmalloc
        0xffffffff81b2cf50, --kasan_remove_zero_shadow
        0xffffffff81b2c4e0, --kasan_report_invalid_free
        0xffffffff81b2cda0, --kasan_report
        0xffffffff81b2cd10, --kdo_kasan_report
        0xffffffff81b2c4e0, --kasan_report_invalid_free
        0xffffffff81b2e5f0, --kasan_save_alloc_info
        0xffffffff81b2e610, --kasan_save_free_info
        0xffffffff81b2bae0, --kasan_save_stack
        0xffffffff8c9f4a80, --kasan_set_multi_shot
        0xffffffff81b2bb40, --kasan_set_track
        0xffffffff8c9bb330, --kasan_shallow_populate_p4ds
        0xffffffff81b2bc10, --kasan_unpoison_task_stack
        0xffffffff81b2bc30, --kasan_unpoison_task_stack_below
        0xffffffff81b2bbf0, --__kasan_unpoison_range_default
        0xffffffff81b2bc00, --__kasan_unpoison_range
        0xffffffff81b2bc80, --__kasan_unpoison_pages
        0xffffffff81b2f610, --__kasan_unpoison_vmalloc
        0xffffffff81b2bc50, --__kasan_unpoison_pages_default
        0xffffffff81b2bd70, --__kasan_unpoison_object_data
        0xffffffff81b2f090, --kasan_unpoison_default
        0xffffffff81b2f100, --kasan_unpoison
        0xffffffff81b2bd50, --__kasan_unpoison_object_data_default
        0xffffffff81b2f090, --kasan_unpoison_default
        0xffffffff81b2bc10, --kasan_unpoison_task_stack
        0xffffffff81b2bc30, --kasan_unpoison_task_stack_below
        0xffffffff81b2bc30, --kasan_unpoison_task_stack_below
        0xffffffff87bb05e0, --kdo_copy_from_user
        0xffffffff87bafef0, --kdo_get_user
        0xffffffff87bb06d0, --kdo_init
        0xffffffff81b2cd10, --kdo_kasan_report
        0xffffffff81b2cd10, --kdo_kasan_report
        0xffffffff87bb0490, --kdo_post_store_hook
        0xffffffff87bb11e0, --kdo_sanitizer_cov_init
        0xffffffff87bb1250, --kdo_sanitizer_cov_read
        0xffffffff87bb1160, --kdo_sanitizer_cov_trace_copy_from_user
        0xffffffff87bb10e0, --kdo_sanitizer_cov_trace_memintrinsic
        0xffffffff87bb1060, --kdo_sanitizer_cov_trace_store
        0xffffffff87bb1270, --kdo_sanitizer_cov_write
        0xffffffff87baff00, --kdo_set_storedonheap
        0xffffffff87bb02d0, --kdo_store_hook
        0xffffffff87baff70, --kdo_taint_val_stored_on_heap
    },
    filter_addr_end = {
        0xffffffff81b2c015, --____kasan_kfree_large
        0xffffffff81b2bed3, --____kasan_slab_free
        0xffffffff81b2c4d4, --__kasan_check_byte
        0xffffffff81b2eec1, --__kasan_check_read
        0xffffffff81b2eee4, --__kasan_check_write
        0xffffffff81b2bdc2, --__kasan_init_slab_obj
        0xffffffff81b2c015, --____kasan_kfree_large
        0xffffffff81b2bf76, --__kasan_kfree_large
        0xffffffff81b2c327, --__kasan_kmalloc
        0xffffffff81b2c3cb, --__kasan_kmalloc_large
        0xffffffff81b2c3cb, --__kasan_kmalloc_large
        0xffffffff81b2c49b, --__kasan_krealloc
        0xffffffff81b2bdb0, --__kasan_poison_object_data
        0xffffffff81b2bcdd, --__kasan_poison_pages
        0xffffffff81b2bd41, --__kasan_poison_slab
        0xffffffff81b2f6e8, --__kasan_poison_vmalloc
        0xffffffff81b2c29a, --__kasan_slab_alloc
        0xffffffff81b2bed3, --____kasan_slab_free
        0xffffffff81b2c1dc, --__kasan_slab_free_mempool
        0xffffffff81b2bdde, --__kasan_slab_free
        0xffffffff81b2c1dc, --__kasan_slab_free_mempool
        0xffffffff81b2bd86, --__kasan_unpoison_object_data
        0xffffffff81b2bd64, --__kasan_unpoison_object_data_default
        0xffffffff81b2bd64, --__kasan_unpoison_object_data_default
        0xffffffff81b2bcab, --__kasan_unpoison_pages
        0xffffffff81b2bc79, --__kasan_unpoison_pages_default
        0xffffffff81b2bc79, --__kasan_unpoison_pages_default
        0xffffffff81b2bbfb, --__kasan_unpoison_range_default
        0xffffffff81b2bc0d, --__kasan_unpoison_range
        0xffffffff81b2bbfb, --__kasan_unpoison_range_default
        0xffffffff81b2f683, --__kasan_unpoison_vmalloc
        0xffffffff87bb05d6, --__kdo_asan_memcpy
        0xffffffff87bb0536, --__kdo_asan_memmove
        0xffffffff8c9f4a7f, --early_kasan_fault
        0xffffffff81b2d738, --kasan_add_zero_shadow
        0xffffffff81b2ba3b, --kasan_addr_to_slab
        0xffffffff81b2db89, --kasan_byte_accessible
        0xffffffff81b2e3f8, --kasan_cache_create
        0xffffffff81b2db99, --kasan_cache_shrink
        0xffffffff81b2dbbc, --kasan_cache_shutdown
        0xffffffff81b2db5b, --kasan_check_range
        0xffffffff81b2e8f2, --kasan_complete_mode_report_info
        0xffffffff81b3024f, --kasan_cpu_offline
        0xffffffff81b301dd, --kasan_cpu_online
        0xffffffff8c9f4b86, --kasan_cpu_quarantine_init
        0xffffffff81b2f610, --kasan_depopulate_vmalloc_pte
        0xffffffff81b2bbe3, --kasan_disable_current
        0xffffffff8c9ba6f6, --kasan_early_init
        0xffffffff81b2bbc3, --kasan_enable_current
        0xffffffff81b2e696, --kasan_find_first_bad_addr
        0xffffffff81b2e417, --kasan_get_alloc_meta
        0xffffffff81b2e6e4, --kasan_get_alloc_size
        0xffffffff81b2e43d, --kasan_get_free_meta
        0xffffffff8c9babeb, --kasan_init
        0xffffffff81b2bdc2, --__kasan_init_slab_obj
        0xffffffff81b2e465, --kasan_init_object_meta
        0xffffffff81b2e465, --kasan_init_object_meta
        0xffffffff8c9ba821, --kasan_map_early_shadow
        0xffffffff87c5281e, --kasan_mem_notifier
        0xffffffff8c9f4b23, --kasan_memhotplug_init
        0xffffffff81b2e923, --kasan_metadata_fetch_row
        0xffffffff81b2e4bb, --kasan_metadata_size
        0xffffffff81b2e31a, --kasan_never_merge
        0xffffffff81b2bcdd, --__kasan_poison_pages
        0xffffffff81b2f6e8, --__kasan_poison_vmalloc
        0xffffffff81b2bd41, --__kasan_poison_slab
        0xffffffff81b2bdb0, --__kasan_poison_object_data
        0xffffffff81b2f056, --kasan_poison
        0xffffffff81b2f082, --kasan_poison_last_granule
        0xffffffff81b2f082, --kasan_poison_last_granule
        0xffffffff87bda392, --kasan_populate_early_shadow
        0xffffffff8c9f4b35, --kasan_populate_early_vm_area_shadow
        0xffffffff8c9bae1d, --kasan_populate_p4d
        0xffffffff8c9bb330, --kasan_populate_pmd
        0xffffffff8c9bb04b, --kasan_populate_pud
        0xffffffff8c9ba954, --kasan_populate_shadow
        0xffffffff8c9ba888, --kasan_populate_shadow_for_vaddr
        0xffffffff8c9ba888, --kasan_populate_shadow_for_vaddr
        0xffffffff81b2f2d2, --kasan_populate_vmalloc_pte
        0xffffffff81b2f1de, --kasan_populate_vmalloc
        0xffffffff81b2f2d2, --kasan_populate_vmalloc_pte
        0xffffffff81b2f4d5, --kasan_populate_vmemmap_pte
        0xffffffff81b2f331, --kasan_populate_vmemmap
        0xffffffff81b2f4d5, --kasan_populate_vmemmap_pte
        0xffffffff81b2ec88, --kasan_print_address_stack_frame
        0xffffffff81b2e997, --kasan_print_aux_stacks
        0xffffffff81b2f9a1, --kasan_quarantine_put
        0xffffffff81b2fb0f, --kasan_quarantine_reduce
        0xffffffff81b2fef6, --kasan_quarantine_remove_cache
        0xffffffff81b2e5ee, --kasan_record_aux_stack_noalloc
        0xffffffff81b2e551, --kasan_record_aux_stack
        0xffffffff81b2e5ee, --kasan_record_aux_stack_noalloc
        0xffffffff81b2f58c, --kasan_release_vmalloc
        0xffffffff81b2d6ed, --kasan_remove_zero_shadow
        0xffffffff81b2c5df, --kasan_report_invalid_free
        0xffffffff81b2cf42, --kasan_report
        0xffffffff81b2cd95, --kdo_kasan_report
        0xffffffff81b2c5df, --kasan_report_invalid_free
        0xffffffff81b2e610, --kasan_save_alloc_info
        0xffffffff81b2e64f, --kasan_save_free_info
        0xffffffff81b2bb3a, --kasan_save_stack
        0xffffffff8c9f4a92, --kasan_set_multi_shot
        0xffffffff81b2bbaf, --kasan_set_track
        0xffffffff8c9bb3a1, --kasan_shallow_populate_p4ds
        0xffffffff81b2bc24, --kasan_unpoison_task_stack
        0xffffffff81b2bc4b, --kasan_unpoison_task_stack_below
        0xffffffff81b2bbfb, --__kasan_unpoison_range_default
        0xffffffff81b2bc0d, --__kasan_unpoison_range
        0xffffffff81b2bcab, --__kasan_unpoison_pages
        0xffffffff81b2f683, --__kasan_unpoison_vmalloc
        0xffffffff81b2bc79, --__kasan_unpoison_pages_default
        0xffffffff81b2bd86, --__kasan_unpoison_object_data
        0xffffffff81b2f0f4, --kasan_unpoison_default
        0xffffffff81b2f165, --kasan_unpoison
        0xffffffff81b2bd64, --__kasan_unpoison_object_data_default
        0xffffffff81b2f0f4, --kasan_unpoison_default
        0xffffffff81b2bc24, --kasan_unpoison_task_stack
        0xffffffff81b2bc4b, --kasan_unpoison_task_stack_below
        0xffffffff81b2bc4b, --kasan_unpoison_task_stack_below
        0xffffffff87bb06c4, --kdo_copy_from_user
        0xffffffff87bafef6, --kdo_get_user
        0xffffffff87bb06f7, --kdo_init
        0xffffffff81b2cd95, --kdo_kasan_report
        0xffffffff81b2cd95, --kdo_kasan_report
        0xffffffff87bb0496, --kdo_post_store_hook
        0xffffffff87bb1249, --kdo_sanitizer_cov_init
        0xffffffff87bb1266, --kdo_sanitizer_cov_read
        0xffffffff87bb11d2, --kdo_sanitizer_cov_trace_copy_from_user
        0xffffffff87bb1152, --kdo_sanitizer_cov_trace_memintrinsic
        0xffffffff87bb10d2, --kdo_sanitizer_cov_trace_store
        0xffffffff87bb1363, --kdo_sanitizer_cov_write
        0xffffffff87baff65, --kdo_set_storedonheap
        0xffffffff87bb048d, --kdo_store_hook
        0xffffffff87bb00c0, --kdo_taint_val_stored_on_heap
    },
}
    